[project]
name = "group25082026"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Egor V", email = "“john@email.com”" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
group25082026 = "group25082026:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
